#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --nodelist=autobot-1-6
#SBATCH --partition=short
#SBATCH --cpus-per-task=4
#SBATCH --time=3-12:00:00
#SBATCH --gres=gpu:10
#SBATCH --mem=40G
#SBATCH -o /home/xlin3/Projects/PlasticineLab/pykeops.out # STDOUT
#SBATCH -e /home/xlin3/Projects/PlasticineLab/pykeops.err # STDERR
set -x
set -u
set -e
srun hostname
module load singularity
module load cuda-11.1.1
cd /home/xlin3/Projects/PlasticineLab
singularity exec -B /opt/ --nv /home/xlin3/softgym_containers/softgymcontainer_v3.simg /bin/bash -c '. ./prepare_1.0.sh && export EGL_GPU=$SLURM_JOB_GRES && echo $EGL_GPU && python /home/xlin3/Projects/PlasticineLab/compile_pykeops/compile.py'
