#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --partition=visg
#SBATCH --nodelist=visg[52]
#SBATCH --cpus-per-task=4
#SBATCH --time=3-12:00:00
#SBATCH --gres=gpu:1
#SBATCH --mem=40G
set -x
set -u
set -e
srun hostname
echo hostname
pwd
source ~/.bashrc
cd $XINGYUPLB
python /home/xlin3/Projects/PlasticineLab/compile_pykeops/compile.py