#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --partition=GPU
#SBATCH --nodelist=compute-0-9
#SBATCH --cpus-per-task=4
#SBATCH --time=480:00:00
#SBATCH --gres=gpu:4
#SBATCH --mem=40G

set -x
set -u
set -e
srun hostname
module load singularity
cd /home/hanwenq/Projects/PlasticineLab
singularity exec --nv /home/xlin3/softgym_containers/softgymcontainer_v4.simg /bin/bash -c '. ./prepare_1.0.sh && export PATH=$PATH:/usr/local/cuda/bin  && export EGL_GPU=$SLURM_JOB_GRES && echo $EGL_GPU && python /home/hanwenq/Projects/PlasticineLab/compile_pykeops/compile.py'
